spring:
  profiles:
    group:
      local: localDB,jasypt, jpa, aws ,jwt ,oauth , redis
      test: testDB, jasypt, jpa, aws , jwt ,oauth, redis
    active: local
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
